export const localizations = {
	english: {
		language: "English",
		title: "Just The Tip",
		billTotal: "Bill Total",
		tipPercent: "Tip %",
		roundTip: "Round Tip",
		roundTotal: "Round Total",
		tip: "Tip",
		total: "Total",
		split: "Split?",
		splitTip: "Split Tip",
		splitTotal: "Split Total",
		splitPeople: "Number of People",
		reset: "Reset",
		tipValues: ["10%", "15%", "20%", "25%"],
		roundValues: ["N/A", "Down", "Up"],
		yes: "Yes",
		no: "No",
		settings: "Settings",
		share: "Share",
		theme: "Theme",
		dark: "Dark",
		light: "Light",
		highContrast: "High Contrast",
		languageWord: "Language",
	},
	spanish: {
		language: "Spanish",
		title: "Solo la Propina",
		billTotal: "Total de la Cuenta",
		tipPercent: "Propina %",
		roundTip: "Redondear Propina",
		roundTotal: "Redondear Total",
		tip: "Propina",
		total: "Total",
		split: "Dividir?",
		splitTip: "Dividir Propina",
		splitTotal: "Dividir Total",
		splitPeople: "Número de Personas",
		reset: "Reiniciar",
		tipValues: ["10%", "15%", "20%", "25%"],
		roundValues: ["N/A", "Abajo", "Arriba"],
		yes: "Si",
		no: "No",
		settings: "Configuraciones",
		share: "Compartir",
		theme: "Tema",
		dark: "Oscuro",
		light: "Claro",
		highContrast: "Alto Contraste",
		languageWord: "Idioma",
	},
};
